server:
  port: 8081
  servlet:
    context-path: /api
  address: 0.0.0.0
spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://服务器ip/user-center?useUnicode=true&characterEncoding=utf8
    username: root
    password: 密码
  session:
    timeout: 86400 #session失效时间一天
mybatis-plus:
  type-aliases-package: com.hex.usercenter.mapper
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete #逻辑删除字段
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)