spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://服务器ip/user-center?useUnicode=true&characterEncoding=utf8
    username: root
    password: 密码
  session:
    timeout: 86400 #session失效时间一天